---
apt_cache_valid_time: 86400

php_fpm_pool_defaults:
  pm: dynamic
  pm.max_children: 50
  pm.start_servers: 10
  pm.min_spare_servers: 5
  pm.max_spare_servers: 10
  listen.owner: www-data
  listen.group: www-data
  listen.mode: '0660'

php_fpm_apt_packages:
  - php5-fpm

php_fpm_yum_packages:
  - php-fpm

php_fpm_default_pool:
  delete: yes
  name: www.conf

php_fpm_ini:
 - option: "engine"
   section: "PHP"
   value: "1"
 - option: "error_reporting"
   section: "PHP"
   value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
 - option: "short_open_tag"
   section: "PHP"
   value: "1"
 - option: "date.timezone"
   section: "PHP"
   value: "Europe/Warsaw"
 
php_fpm_config:
 - option: "error_log"
   section: "global"
   value: "/var/log/php5-fpm.log"
