---
# These tasks install http and the php modules.

- name: Install apache 2.4
  apt: name={{ item }} state=present
  with_items:
   - apache2-mpm-event

- name: enable mod_proxy_fcgi
  apache2_module: state=present name=proxy_fcgi

- name: apache service state
  service: name=apache2 state=started enabled=yes

- name: Create apache2 vhosts
  template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ item.servername }}.conf
    owner: root
    group: root
    mode: 0640
  with_items: apache_vhosts
